spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbook?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Seoul&use.JDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username : root
    password : 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
